//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalMania
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManiaEntities : DbContext
    {
        public HotelManiaEntities()
            : base("name=HotelManiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblFood> tblFoods { get; set; }
        public virtual DbSet<tblFoodBooking> tblFoodBookings { get; set; }
        public virtual DbSet<tblFoodBookingDetail> tblFoodBookingDetails { get; set; }
        public virtual DbSet<tblHotel> tblHotels { get; set; }
        public virtual DbSet<tblHotelBooking> tblHotelBookings { get; set; }
        public virtual DbSet<tblImage> tblImages { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
