//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalMania
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotel()
        {
            this.tblHotelBookings = new HashSet<tblHotelBooking>();
            this.tblImages = new HashSet<tblImage>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PerHourPPC { get; set; }
        public Nullable<long> TotalPersonCapacity { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Location { get; set; }
        public Nullable<long> ParkingCapacity { get; set; }
        public Nullable<bool> IsAvailible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelBooking> tblHotelBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImage> tblImages { get; set; }
    }
}
